# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data and stuff
email: neuhofmo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 This blog is going to be about data science, python, computational biology 
 and occasionally other topics that made me excited for at least a moment. 
 As you can understand, this blog is dedicated to the things that excite me most 
 (at least professionally; otherwise it would be 100% about dogs).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NeuhofMoran
github_username:  neuhofmo

# Google Analytics
google_analytics: UA-113901221-1

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

timezone: Asia/Jerusalem
# show_downloads: false
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
